build: update Vercel deployment step to use deploymentUrl and handle errors

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -131,7 +131,7 @@ jobs:
     needs: build
     environment:
       name: Preview
-      url: ${{ steps.vercel_preview.outputs.url }}
+      url: ${{ steps.vercel_preview.outputs.deploymentUrl }}
     permissions:
       contents: read
     steps:
@@ -167,15 +167,21 @@ jobs:
           echo "🔍 Vercel output directory structure:"
           find ./ -type f -not -path "*/node_modules/*" | sort
 
-      - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
-
-      - name: Deploy to Vercel
-        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
-
       - name: Deploy to Vercel (Preview)
         id: vercel_preview
         run: |
-          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --output=json > prod.json
-          # URL extrahieren und als Schritt-Output setzen:
-          echo "url=$(jq -r '.url' prod.json)" >> $GITHUB_OUTPUT
+
+          vercel deploy --yes --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt 2>error.txt
+
+          # check the exit code
+          code=$?
+          if [ $code -eq 0 ]; then
+              # Now you can use the deployment url from stdout for the next step of your workflow
+              deploymentUrl=`cat deployment-url.txt`
+              echo "deploymentUrl=$deploymentUrl" >> "$GITHUB_OUTPUT"
+
+          else
+              # Handle the error
+              errorMessage=`cat error.txt`
+              echo "There was an error: $errorMessage"
+          fi
